version: "3"

networks:
    paczkomat:

services:
    outgetdotnet:
        build: .
        ports:
            - "5000:443"
        depends_on:
            - sql
        command: ["dotnet", "ef", "database update"]
        networks:
            - paczkomat
    sql:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        networks:
            - paczkomat
    server:
        #image: outgetangular
        build:
            context: .././OutGetAngular
            dockerfile: Dockerfile
        ports:
            - "3334:80"
        tty: true
        expose:
            - "80" 
        stdin_open: true
        environment:
            - MODE=dev